# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py311

[testenv]
# install pytest in the virtualenv where commands will be executed
deps =
    pytest
    sh

extras = test
commands =
    # NOTE: you can run any command line tool here - not just tests
    pytest {posargs}

[pytest]
# testing mountutil requires Linux distro and sudo password input. Skip it by default
; addopts = --ignore=yautil/tests/test_mountutil.py
