name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Run tox
        run: tox
